### ISSUE TITLE
Keep one file synchronized

### ISSUE THREAD

**Issue by locusf** [beidl/harbour-owncloud#20] opened 2018-04-26 06:15 UTC
For a feature request, I'd suggest a way to keep a single file synchronized between owncloud and device. I use Zutun.txt app and I'd like to keep my todo.txt synched between my phone and owncloud.

**Comment by beidl** [comment] 2018-07-22 23:07
Part of https://github.com/beidl/harbour-owncloud/projects/1#card-11392439

**Comment by beidl** [comment] 2018-07-22 23:09
Duplicate of #17 due to recent changes in development branch, synching files and directories will be handled equally.

**Closed by beidl** 2018-07-22 23:09 UTC
